### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by StevenZzz07** [luost26/diffusion-point-cloud#1]
Hi, first thanks for your inspiring work! Point cloud rendering figures in your paper are so beautiful, such as these vivid shadows. How do you draw it? Using open3d, meshlab or other programmes?

Thanks!
![image](https://user-images.githubusercontent.com/56421441/110414055-20626300-80ca-11eb-8867-8f20a5e0375f.png)

**Comment by luost26** [comment]
Hi,

Please refer to [PointFlowRenderer](https://github.com/zekunhao1995/PointFlowRenderer). Thanks!

**Comment by StevenZzz07** [comment]
Thank you! I will check it out.
