### ISSUE TITLE
请问如下两个错误怎么解决：1、error in nnd Output: invalid device function。2、AssertionError: can only join a child process

### ISSUE THREAD

**Issue by xieliang11111** [luost26/diffusion-point-cloud#10]
问题1：
![image](https://user-images.githubusercontent.com/22213368/125911424-e5a65b9b-d89a-4a0a-97a5-cec3431c6e70.png)

问题2：
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb8cf914320>
Traceback (most recent call last):
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process

**Comment by WN1695173791** [comment]
我也有同样问题，网上查是在编译时的makefile文件中的算力与自己GPU的型号不匹配，但是我修改完仍然不起作用，请问你解决了吗？方便的话加QQ(1695173791)一起讨论

**Comment by InfyIT-fa** [comment]
Hi, I have a quick question, did you able to build StructuralLossesBacken ? If yes, then would you please let me know how ? I am getting a g++ error ( created an issues already but no response yet).

**Comment by luost26** [comment]
Hi all,

EMD_CD functions are for validation purpose only. The training doesn't rely on them, so you may remove this part of codes in the training script. I will also release a version without them later.

**Comment by luost26** [comment]
As for the AssertionError, it seems that `tqdm` caused this error according to https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845/9

Could you try replacing `from tqdm.auto import tqdm` with `from tqdm import tqdm` in the training script ?

**Comment by GloryyrolG** [comment]
I think it still does not work by doing so.

**Comment by GloryyrolG** [comment]
Hi Shitong,

Good Job and appreciate for the public source code. Furthermore, can you release more details on the configuration where your repo produces the results in the paper? As discussed above, the current code seems a bit hard for us to run smoothly.

Thanks & Best regards,
