### ISSUE TITLE
/usr/bin/ld: cannot find -lmake_pytorch collect2: error: ld returned 1 exit status error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by InfyIT-fa** [luost26/diffusion-point-cloud#13]
Hi,

I have built "StructuralLoss" successfully. But for the evaluation_metrics.py, I found the problem that it can not import " from evaluation.StructuralLosses.StructuralLossesBackend import ApproxMatch, MatchCost, MatchCostGrad" in match_cost.py ( folder: pytorch_structural_losses) because "StructuralLossesBackend"  is not created yet. 

So, I tried to go to "pytorch_structural_losses" folder and run the "setup.py" file using the following command: 

**python setup.py build_ext**

But getting errors. ( I have attached a screenshot) . I tried both python 3.7 and 3.8 but getting the same errors.

I tried multiple times but could not able to find it. Please let me know how to fix this issue?

<img width="746" alt="Screen Shot 2021-08-05 at 6 09 25 PM" src="https://user-images.githubusercontent.com/86115631/128447469-94637ff4-b96f-400f-8d55-50c7ee672da3.png">

**Comment by titaniumrain** [comment]
see if this helps - https://github.com/chrischoy/MakePytorchPlusPlus/issues/1
