### ISSUE TITLE
How to Visualization the ./result/GEN_Ours_airplane_xxxxxxx/out.npy file?

### ISSUE THREAD

**Issue by XDUWQ** [luost26/diffusion-point-cloud#14]
Hi！In Generating task，after `python test_gen.py`，how to Visualization the ./result/GEN_Ours_airplane_xxxxxxx/out.npy file?

**Comment by luost26** [comment]
Hi,
Please check this out: https://stackoverflow.com/questions/1985856/how-to-make-a-3d-scatter-plot-in-python
