### ISSUE TITLE
Point cloud to mesh

### ISSUE THREAD

**Issue by Siziff** [luost26/diffusion-point-cloud#23]
Hello:) I got a point cloud, but I don't know how to wrap it in a mesh, I tried a lot of methods, but they all turn out too not pretty (example in the picture). Do you know how to improve the point cloud to get a better mesh shape? or maybe you know cool algorithms for getting a beautiful mesh shape?
![image](https://user-images.githubusercontent.com/42972554/204809975-64c574da-ca92-4092-bff5-9849e96193d8.png)

**Comment by luost26** [comment]
I think this one is the sota: https://arxiv.org/abs/2106.03452
