### ISSUE TITLE
loss is to high and am almost invariable

### ISSUE THREAD

**Issue by jackiezhang11** [luost26/diffusion-point-cloud#24]
Training my own dataset,Loss maintain 60 after execute train_gen.py.
The parameter settings are basically unchanged.
How can I resolve this question?

**Comment by luost26** [comment]
https://github.com/luost26/diffusion-point-cloud/issues/20#issuecomment-1258238537

**Comment by jackiezhang11** [comment]
I got it! Thanks for your response

**Comment by jackiezhang11** [comment]
Thank you for your reply.I get it.
But I have a problem,&nbsp;dataset cannot be downloaded after download half of dataset.
Do you have any other downloading methods？
or How can I download dataset success?







zgg
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luost26/diffusion-point-cloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luost26/diffusion-point-cloud] loss is to high and am almost invariable (Issue #24)





 
#20 (comment)
