### ISSUE TITLE
About the Drawing of 3D point cloud generation Images in the paper

### ISSUE THREAD

**Issue by ZhouHaoWa** [luost26/diffusion-point-cloud#25]
How to draw the image generated by the beautiful 3D Point Cloud Generation in this article, can anybody share the code of the drawing? Since i like it very much.

**Comment by luost26** [comment]
https://github.com/zekunhao1995/PointFlowRenderer

**Comment by ZhouHaoWa** [comment]
Sorry to bother you again, I refer to your guidance and use the pointflow_fig_colorful.py function and the mitsuba toolkit, but finally generate an exr file, can I only use third-party software such as ps to open it? Thanks again for your reply!

**Comment by CaineGu** [comment]
> Sorry to bother you again, I refer to your guidance and use the pointflow_fig_colorful.py function and the mitsuba toolkit, but finally generate an exr file, can I only use third-party software such as ps to open it? Thanks again for your reply!

you can use adobe illustrator to open exr files
