### ISSUE TITLE
Which place do you use the autoencoder ?

### ISSUE THREAD

**Issue by PPGGG** [luost26/diffusion-point-cloud#27]
I noticed that in your code, you train an autoencoder, but in the generation code, it seems that you don't use it. So you train an autoencoder and generator but in the final you just use the generator ?

**Comment by luost26** [comment]
Auto-encoding and generation were treated as two different tasks then.

**Comment by PPGGG** [comment]
Oh i see. Thank you very much.

**Comment by wxf-0415** [comment]
> Oh i see. Thank you very much.

hi, i don't konw the difference of tow files. Could you tell me the details？
