### ISSUE TITLE
make: *** [objs/cuda/approxmatch.o] Error 139

### ISSUE THREAD

**Issue by dsw-jlu-rgzn** [luost26/diffusion-point-cloud#9]
hello , when run the following code
make clean
make
i get the problem
![image](https://user-images.githubusercontent.com/84772583/125599612-6f559f89-12c5-4134-9eb8-c969a3e78c2c.png)
how can i fix it 
and my nvcc -V is 10.0
![image](https://user-images.githubusercontent.com/84772583/125599717-f9c0d4fb-ad73-4d83-8f7a-5c447215cc5c.png)

**Comment by luost26** [comment]
I will release a version that doesn't require compiling CUDA extensions soon.

**Comment by InfyIT-fa** [comment]
Hi, I have a quick question, did you able to build StructuralLossesBacken ? If yes, then would you please let me know how ? I am getting a g++ error ( created an issues already but no response yet).
